import type { User, Product, Service, Store, Booking, Payment, Report, DashboardStats } from "@/types/api";

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalUsers: 12847,
  totalVendors: 1256,
  totalProducts: 4892,
  totalServices: 2341,
  totalBookings: 8934,
  totalRevenue: 284750.00,
  pendingApprovals: 47,
  activeReports: 12,
};

// Users
export const mockUsers: User[] = [
  {
    id: "usr_001",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@email.com",
    phoneNumber: "+1 (555) 123-4567",
    roles: ["customer"],
    activeRole: "customer",
    isEmailVerified: true,
    isPhoneNumberVerified: true,
    countryName: "United States",
    countryCode: "US",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "usr_002",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@email.com",
    phoneNumber: "+44 7911 123456",
    roles: ["vendor"],
    activeRole: "vendor",
    isEmailVerified: true,
    isPhoneNumberVerified: false,
    countryName: "United Kingdom",
    countryCode: "GB",
    vendorOnboardingStatus: "approved",
    subscriptionType: "monthly",
    isSubscriptionActive: true,
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "usr_003",
    firstName: "Amara",
    lastName: "Okonkwo",
    email: "amara.okonkwo@email.com",
    phoneNumber: "+234 801 234 5678",
    roles: ["vendor", "customer"],
    activeRole: "vendor",
    isEmailVerified: true,
    isPhoneNumberVerified: true,
    countryName: "Nigeria",
    countryCode: "NG",
    vendorOnboardingStatus: "pending",
    subscriptionType: "commission",
    isSubscriptionActive: true,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "usr_004",
    firstName: "Emma",
    lastName: "Williams",
    email: "emma.williams@email.com",
    roles: ["customer"],
    activeRole: "customer",
    isEmailVerified: false,
    isPhoneNumberVerified: false,
    countryName: "United Kingdom",
    countryCode: "GB",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "usr_005",
    firstName: "David",
    lastName: "Miller",
    email: "david.miller@email.com",
    phoneNumber: "+1 (555) 987-6543",
    roles: ["admin"],
    activeRole: "admin",
    isEmailVerified: true,
    isPhoneNumberVerified: true,
    countryName: "United States",
    countryCode: "US",
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: "prod_001",
    name: "Premium Wedding Bouquet",
    description: "Hand-crafted luxury wedding bouquet with fresh roses and peonies",
    price: 299.99,
    currency: "GBP",
    images: ["/placeholder.svg"],
    category: { id: "cat_01", name: "Flowers" },
    vendor: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    status: "approved",
    isDeleted: false,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "prod_002",
    name: "Vintage Lace Veil",
    description: "Elegant cathedral-length vintage lace veil",
    price: 450.00,
    currency: "GBP",
    images: ["/placeholder.svg"],
    category: { id: "cat_02", name: "Accessories" },
    vendor: { id: "usr_003", name: "Amara Okonkwo", email: "amara.okonkwo@email.com" },
    status: "pending",
    isDeleted: false,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "prod_003",
    name: "Custom Wedding Invitations Set",
    description: "Personalized letterpress wedding invitation suite",
    price: 175.00,
    currency: "USD",
    images: ["/placeholder.svg"],
    category: { id: "cat_03", name: "Stationery" },
    vendor: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    status: "approved",
    isDeleted: false,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "prod_004",
    name: "Crystal Tiara",
    description: "Swarovski crystal bridal tiara with pearl accents",
    price: 320.00,
    currency: "GBP",
    images: ["/placeholder.svg"],
    category: { id: "cat_02", name: "Accessories" },
    vendor: { id: "usr_003", name: "Amara Okonkwo", email: "amara.okonkwo@email.com" },
    status: "rejected",
    rejectionReason: "Images do not meet quality standards",
    isDeleted: false,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-08"),
  },
];

// Services
export const mockServices: Service[] = [
  {
    id: "srv_001",
    name: "Full Wedding Photography Package",
    description: "Complete wedding day coverage with two photographers",
    price: 2500.00,
    currency: "GBP",
    duration: 480,
    images: ["/placeholder.svg"],
    category: { id: "cat_04", name: "Photography" },
    store: { id: "store_001", name: "Eternal Moments Studio" },
    vendor: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    status: "approved",
    isDeleted: false,
    isSuspended: false,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "srv_002",
    name: "Bridal Makeup & Hair",
    description: "Professional bridal makeup and hairstyling service",
    price: 350.00,
    currency: "GBP",
    duration: 180,
    images: ["/placeholder.svg"],
    category: { id: "cat_05", name: "Beauty" },
    store: { id: "store_002", name: "Glamour Bridal" },
    vendor: { id: "usr_003", name: "Amara Okonkwo", email: "amara.okonkwo@email.com" },
    status: "pending",
    isDeleted: false,
    isSuspended: false,
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-12"),
  },
  {
    id: "srv_003",
    name: "Wedding DJ & Entertainment",
    description: "Professional DJ services for wedding reception",
    price: 800.00,
    currency: "GBP",
    duration: 360,
    images: ["/placeholder.svg"],
    category: { id: "cat_06", name: "Entertainment" },
    store: { id: "store_003", name: "Party Vibes Entertainment" },
    vendor: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    status: "approved",
    isDeleted: false,
    isSuspended: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

// Stores
export const mockStores: Store[] = [
  {
    id: "store_001",
    name: "Eternal Moments Studio",
    description: "Award-winning wedding photography studio",
    owner: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    location: {
      address: "123 High Street",
      city: "London",
      state: "Greater London",
      zipcode: "W1A 1AA",
      coordinates: [51.5074, -0.1278],
    },
    gallery: ["/placeholder.svg"],
    viewCount: 1523,
    rating: 4.8,
    reviewCount: 127,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "store_002",
    name: "Glamour Bridal",
    description: "Luxury bridal beauty services",
    owner: { id: "usr_003", name: "Amara Okonkwo", email: "amara.okonkwo@email.com" },
    location: {
      address: "45 Victoria Island",
      city: "Lagos",
      state: "Lagos",
      zipcode: "101233",
      coordinates: [6.4541, 3.4234],
    },
    gallery: ["/placeholder.svg"],
    viewCount: 892,
    rating: 4.6,
    reviewCount: 84,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-10"),
  },
];

// Bookings
export const mockBookings: Booking[] = [
  {
    id: "book_001",
    bookingReference: "BK-2024-001",
    user: { id: "usr_001", name: "Sarah Johnson", email: "sarah.johnson@email.com" },
    store: {
      id: "store_001",
      name: "Eternal Moments Studio",
      owner: { id: "usr_002", name: "Michael Chen" },
    },
    serviceType: "Photography",
    serviceDate: new Date("2024-06-15"),
    serviceTime: "10:00",
    pricing: {
      subtotal: 2500.00,
      amountPaid: 500.00,
      remainingBalance: 2000.00,
      currency: "GBP",
    },
    status: "confirmed",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-02"),
  },
  {
    id: "book_002",
    bookingReference: "BK-2024-002",
    user: { id: "usr_004", name: "Emma Williams", email: "emma.williams@email.com" },
    store: {
      id: "store_002",
      name: "Glamour Bridal",
      owner: { id: "usr_003", name: "Amara Okonkwo" },
    },
    serviceType: "Beauty",
    serviceDate: new Date("2024-05-20"),
    serviceTime: "09:00",
    pricing: {
      subtotal: 350.00,
      amountPaid: 350.00,
      remainingBalance: 0,
      currency: "GBP",
    },
    status: "completed",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "book_003",
    bookingReference: "BK-2024-003",
    user: { id: "usr_001", name: "Sarah Johnson", email: "sarah.johnson@email.com" },
    store: {
      id: "store_003",
      name: "Party Vibes Entertainment",
      owner: { id: "usr_002", name: "Michael Chen" },
    },
    serviceType: "Entertainment",
    serviceDate: new Date("2024-06-15"),
    serviceTime: "18:00",
    pricing: {
      subtotal: 800.00,
      amountPaid: 0,
      remainingBalance: 800.00,
      currency: "GBP",
    },
    status: "pending",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
];

// Payments
export const mockPayments: Payment[] = [
  {
    id: "pay_001",
    paymentReference: "PAY-2024-001",
    user: { id: "usr_001", name: "Sarah Johnson", email: "sarah.johnson@email.com" },
    paymentType: "booking",
    status: "completed",
    paymentMethod: "card",
    paymentGateway: "stripe",
    amount: 500.00,
    currency: "GBP",
    paidAt: new Date("2024-03-01"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "pay_002",
    paymentReference: "PAY-2024-002",
    user: { id: "usr_004", name: "Emma Williams", email: "emma.williams@email.com" },
    paymentType: "booking",
    status: "completed",
    paymentMethod: "card",
    paymentGateway: "stripe",
    amount: 350.00,
    currency: "GBP",
    paidAt: new Date("2024-02-20"),
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "pay_003",
    paymentReference: "PAY-2024-003",
    user: { id: "usr_002", name: "Michael Chen", email: "michael.chen@email.com" },
    paymentType: "subscription",
    status: "completed",
    paymentMethod: "card",
    paymentGateway: "stripe",
    amount: 29.99,
    currency: "GBP",
    paidAt: new Date("2024-03-01"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
];

// Reports
export const mockReports: Report[] = [
  {
    id: "rep_001",
    reporter: { id: "usr_001", name: "Sarah Johnson", email: "sarah.johnson@email.com" },
    targetType: "product",
    targetId: "prod_004",
    reason: "Misleading description",
    description: "The product images appear to be stock photos, not actual product",
    status: "pending",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "rep_002",
    reporter: { id: "usr_004", name: "Emma Williams", email: "emma.williams@email.com" },
    targetType: "store",
    targetId: "store_002",
    reason: "Poor service",
    description: "Vendor was unprofessional and late to the appointment",
    status: "reviewing",
    reviewNote: "Contacting vendor for their response",
    reviewedBy: { id: "usr_005", name: "David Miller" },
    reviewedAt: new Date("2024-03-12"),
    createdAt: new Date("2024-03-11"),
    updatedAt: new Date("2024-03-12"),
  },
];

// Revenue chart data
export const mockRevenueData = [
  { month: "Jan", revenue: 18500, bookings: 125 },
  { month: "Feb", revenue: 22300, bookings: 148 },
  { month: "Mar", revenue: 28750, bookings: 189 },
  { month: "Apr", revenue: 32100, bookings: 212 },
  { month: "May", revenue: 38900, bookings: 256 },
  { month: "Jun", revenue: 45200, bookings: 298 },
];

// User growth chart data
export const mockUserGrowthData = [
  { month: "Jan", users: 8500, vendors: 450 },
  { month: "Feb", users: 9200, vendors: 520 },
  { month: "Mar", users: 10100, vendors: 680 },
  { month: "Apr", users: 10800, vendors: 820 },
  { month: "May", users: 11600, vendors: 1020 },
  { month: "Jun", users: 12847, vendors: 1256 },
];
